{% set pypiname = "PyMieScatt" %}
{% set version = "1.7.5.2" %}

package:
  name: {{ pypiname|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 82e13495748d4285ab5b6506ecf484a848140e496f0f9c828bf8279ea6cba0b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - scipy
    - matplotlib
    - shapely

test:
  imports:
    - PyMieScatt

about:
  home: https://github.com/bsumlin/PyMieScatt
  license: MIT
  license_file: LICENSE.md
  summary: A collection of forward and inverse Mie solving routines based on Bohren and Huffman's Mie Theory derivations.

extra:
  recipe-maintainers:
    - kmuehlbauer
