{% set pypiname = "PyMieScatt" %}
{% set version = "1.7.5.1" %}

package:
  name: {{ pypiname|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: acdf1669cbfc2fb2371c4a5406d6d175c1b0021468848608acafed2ac8416c70

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - scipy
    - matplotlib
    - shapely

test:
  imports:
    - PyMieScatt

about:
  home: https://github.com/bsumlin/PyMieScatt
  license: MIT
  license_file: LICENSE.md
  summary: A collection of forward and inverse Mie solving routines based on Bohren and Huffman's Mie Theory derivations.

extra:
  recipe-maintainers:
    - kmuehlbauer
