{% set pypiname = "PyMieScatt" %}
{% set version = "1.7.3" %}

package:
  name: {{ pypiname|lower }}
  version: {{ version }}

source:
  # no recent pypi-tarball available, see https://github.com/bsumlin/PyMieScatt/issues/6
  git_url: https://github.com/bsumlin/{{ pypiname }}
  git_rev: 0e669681b34b1200b0548f7245201e0eef447e9b
  
build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - scipy
    - matplotlib
    - shapely

test:
  imports:
    - PyMieScatt

about:
  home: https://github.com/bsumlin/PyMieScatt
  license: MIT
  license_file: LICENSE.md
  summary: "A collection of forward and inverse Mie solving routines based on Bohren and Huffman's Mie Theory derivations."

extra:
  recipe-maintainers:
    - kmuehlbauer
