{% set pypiname = "PyMieScatt" %}
{% set version = "1.7.5.4" %}

package:
  name: {{ pypiname|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 07a301f1138f5e68164fcf00349bda78be99b8a3211a149b1762f2721b4b6b14

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - scipy
    - matplotlib-base
    - shapely

test:
  imports:
    - PyMieScatt

about:
  home: https://github.com/bsumlin/PyMieScatt
  license: MIT
  license_file: LICENSE.md
  summary: A collection of forward and inverse Mie solving routines based on Bohren and Huffman's Mie Theory derivations.

extra:
  recipe-maintainers:
    - kmuehlbauer
