travis:
  secure:
    BINSTAR_TOKEN: ViXLU4FOd5dbWAOAqZcIwc77L8KyydG4wVgMS6uMWK8Ep5jWtQA+WV0W46l3hlatQ90UA/ERFHZf74xhyRvcB64vSi7ODFMVLplIgr0i0HHd8R/r1/T741dzNA4Yzd25UIxGEkgrdhncWTRLgP9oyEhRXHi2Iey+PcwV1tpO7f2j/AfdTEJ9VF2swnD3ORljAwrhxDz+uOKuTaKLEknk/u1ULOU1hS4W5n0OKCZYSjfvz3eCoUSufc3OUAHYq1DStVuFALDdpde2Wnou5i/ycEnQNuIkBP1G+2P3opqP1d8EkeCVnhgPM2sVxrjAhQXqsqCFytrYql/bcryNIsTumn2U5lU326NFyfl/FvTl6RjjjAA85TDfI6vxtlv/O/RiuV4dJstTx+Iy0TzPAaUyBS5t2pkrNaGMnhRaOjSPiUWBID4wEmu7XLGHD9cqOtNf1yfW+4CVkL4lwrdcgr5hLISxOwU3Xshxqaj5jMSqBSFeKqhFM0On3C46GI+DC8bCoiWC6Q/iqIp4184J687j4vHXsfwF6WhrFWCCuXvyef+RYcKxn60SxGuoLMfqzsR8FtwL1/To7UlU7aEMJz8RXIqhuD38V51XQVcmStHlYNRJVIjDR9HeszoOz5yMquXwmL4Vco6UIf+7eAVu8kJ4wx3QQc9lkqXhoLU/EjVhPpQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
